### ISSUE TITLE
INFOGRAFÍA 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-1-infografia-Anakimberly#1]
[INFOGRAFIA CICLO DE VIDA DEL DESARROLLO DE SOFTWARE.pdf](https://github.com/user-attachments/files/16811718/INFOGRAFIA.CICLO.DE.VIDA.DEL.DESARROLLO.DE.SOFTWARE.pdf)

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica, obtuviste 20%

**Si tiene 10 temas principales, cuenta con desventajas y ventajas, la ortografía está bien y la estrutura es adecuada.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
